package com.diegogmd.filmfollower.data.local.remote

import com.gmdproject.farmlog_project.GlobalVariables
import java.io.File

object ApiConfig {

    // Flip this to switch where the token comes from.
    private const val USE_ENV_FILE = false

    val TMDB_ACCESS_TOKEN: String by lazy {
        if (USE_ENV_FILE) {
            readTokenFromEnvFile()
        } else {
            readTokenFromFallback()
        }
    }

    private fun readTokenFromEnvFile(): String {
        // .env sits one folder above /api:
        // app/src/main/java/com/diegogmd/filmfollower/.env
        val envFile = File("app/src/main/java/com/diegogmd/filmfollower/.env")//Not working

        require(envFile.exists()) {
            "Couldn't find .env at ${envFile.absolutePath}. " +
                    "Adjust the path above, or set USE_ENV_FILE = false."
        }

        val token = envFile.readLines()
            .map { it.trim() }
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .firstOrNull { it.startsWith("READ_ACCESS_TOKEN") }
            ?.substringAfter("=")
            ?.trim()
            ?.trim('"', '\'')

        return token ?: error("READ_ACCESS_TOKEN key not found inside .env")
    }

    private fun readTokenFromFallback(): String {
        // Option B: BuildConfig, generated by Gradle from local.properties.
        // Uncomment once you set that up:
        // return BuildConfig.READ_ACCESS_TOKEN

        // Or, quick and dirty for local testing only (don't commit this):
        return GlobalVariables.TMDB_ACCESS_TOKEN
    }
}